config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "expenses#monthly"
  
  get "expenses" => "expenses#monthly"

  resources :expenses do
    collection do
      get :month
      get :week
      get :weekly
    end
  end

  resources :expense_types

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/colour.rb
class Colour < ApplicationRecord
  has_many :expense_types, dependent: :destroy

  # validations
  validates_presence_of :gradient
  validates_presence_of :primary
  end

app/models/expense.rb
class Expense < ApplicationRecord
  # asociations
  belongs_to :expense_type

  # validations
  validates_presence_of :amount
  validates_presence_of :spent_on

  # scopes
  scope :ordered, -> { order(spent_on: :desc) }

  def to_s
    if extra_info.present?
      "#{expense_type.name} - #{extra_info}"
    else
      expense_type.name
    end
  end

  # group all expenses by month
  def self.monthly
    Expense.connection.select_all("SELECT MONTH(spent_on) AS month, YEAR(spent_on) AS year, SUM(amount) AS amount FROM `expenses` GROUP BY YEAR(spent_on), MONTH(spent_on) ORDER BY year DESC, month DESC") 
  end

  # select all expenses for a given month
  def self.month(month, year)
    Expense.where("YEAR(spent_on) = ? AND MONTH(spent_on) = ?", year, month).ordered
  end

  def self.monthly_by_type(month, year, expense_type)
    Expense.where("YEAR(spent_on) = ? AND MONTH(spent_on) = ? AND expense_type_id = ?", year, month, expense_type).ordered
  end

  # group all exepenses by week 
  def self.weekly 
    Expense.connection.select_all("SELECT WEEK(spent_on) AS week, MONTH(spent_on) AS month, YEAR(spent_on) AS year, SUM(amount) AS amount FROM `expenses` GROUP BY week, month, year ORDER BY year DESC, week DESC") 
  end

  def self.week(month, week, year)
    Expense.where("YEAR(spent_on) = ? AND MONTH(spent_on) = ? AND WEEK(spent_on) = ?", year, month, week).ordered
  end

  def self.weekly_by_type(week, year, expense_type)
    Expense.where("YEAR(spent_on) = ? AND WEEK(spent_on) = ? AND expense_type_id = ?", year, week, expense_type).ordered
  end

  def gradient
    expense_type.colour.gradient
  end
end

app/models/expense_type.rb
class ExpenseType < ApplicationRecord
  # Associations
  has_many :expenses, dependent: :destroy
  belongs_to :colour

  # Validations
  validates_presence_of :name

  # Scope 
  scope :ordered, -> { order(name: :asc) }

  def to_s
    name
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/expense_types_controller.rb
class ExpenseTypesController < ApplicationController
  before_action :set_expense_types, only: [:index]

  def index
  end

  def new
    @expense_type = ExpenseType.new
  end

  def create
    @expense_type = ExpenseType.new(expense_type_params)

    if @expense_type.save
      redirect_to expense_types_path
    else
      render :new
    end
  end

  private

  def set_expense_types
    @expense_types = ExpenseType.all
  end

  def expense_type_params
    params
      .require(:expense_type)
      .permit(:colour_id, :name)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_monthly_expenses, only: [:monthly]
  before_action :set_weekly_expenses, only: [:weekly]
  before_action :set_month, only: [:month]
  before_action :set_week, only: [:week]
  
  # expenses by months
  def monthly
  end

  # expenses for a given month
  def month
  end

  # expenses by weeks
  def weekly
  end

  # expenses for a given week
  def week
  end

  def new
    @expense = Expense.new
  end

  def edit
  end

  def create
    @expense = Expense.new(expense_params)
    if @expense.save
      redirect_to expenses_path
    else
      render :new
    end
  end

  def update
    if @expense.update(expense_params)
      redirect_to expenses_path
    else
      render :edit
    end
  end

  private

  def set_monthly_expenses
    @expenses = Expense.monthly
  end

  def set_month
    if params[:expense_type].present?
      @expenses = Expense.monthly_by_type(params[:month], params[:year], params[:expense_type])    
    else
      @expenses = Expense.month(params[:month], params[:year])    
    end
  end

  def set_weekly_expenses
    @expenses = Expense.weekly
  end

  def set_week
    if params[:expense_type].present?
      @expenses = Expense.weekly_by_type(params[:week], params[:year], params[:expense_type])    
    else
      logger.debug("in here")
      @expenses = Expense.week(params[:month], params[:week], params[:year])    
    end
  end

  def expense_params
    params
      .require(:expense)
      .permit(:amount, :extra_info, :expense_type_id, :spent_on, :week)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_date(number)
    months = [
      "January", "February", "March", "April", 
      "May", "June", "July", "August", "September", 
      "October", "November", "December"
    ]
    months[number - 1]
  end
end

app/helpers/expense_types_helper.rb
module ExpenseTypesHelper
  def get_gradient(expense_type)
    expense_type.colour.first.gradient
  end


end

app/helpers/expenses_helper.rb
module ExpensesHelper
  def expenses_bar(expenses)
    overall_total = expenses.sum { |r| r[:amount] }
    expense_types = expenses.map {|x| {name: x.expense_type.name, total: 0.0, percent: 0.0, color: x.expense_type.colour}}.uniq
    
    expenses.each do |expense| 
        current_expense_type = expense_types.select {|x| x[:name] == expense.expense_type.name  }.last
        current_expense_type[:total] += expense.amount.to_f
    end
    
    expense_types.each do |expense_type| 
        expense_type[:percent] = (expense_type[:total] * 100.0) / overall_total.to_f
    end

    render(partial: 'bar', locals: { expense_types: expense_types })
  end
end

app/helpers/ordinal_helper.rb
module OrdinalHelper
  def ordinal(number)
    abs_number = number.to_i.abs
  
    if (11..13).include?(abs_number % 100)
      "th"
    else
      case abs_number % 10
        when 1; "st"
        when 2; "nd"
        when 3; "rd"
        else    "th"
      end
    end
  end
  
  def ordinalize(number)
    "#{number}#{ordinal(number)}"
  end
end

app/views/expense_types/_form.html.erb
<%= form_with model: @expense_type, local: true do |f| %>
  <div class="field">
    <div class="select">
      <%= f.text_field(:name, maxlength: 20, placeholder: "Name") %>
    </div>
  </div>

  <div class="field">
    <div class="select">
      <%= f.collection_select(:colour_id, Colour.all, :id, :primary, required: true, selected: 1) %>
    </div>
  </div>

  <%= f.submit class: "button is-primary" %>
<% end %>

<%= link_to "Back", expense_types_path %>

app/views/expense_types/index.html.erb
<div class="wrapper">
  <h1> Expense types </h1>
  <% @expense_types.each do |expense_type| %>
      <div class="tile">
        <div class="tile-inner"> 
          <div class="tile-left">
            <div class="expense-icon" style="background:<%= expense_type.colour.gradient %>;">
              <%= expense_type.to_s[0,2] %>
            </div>
            <div class="tile-type">
              <%= expense_type %>
            </div>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/expense_types/new.html.erb
<div class="wrapper">
  <h1>New expense type</h1>
  <%= render "form" %>
</div>

app/views/expenses/_bar.html.erb
<% @expense_types = expense_types.sort_by! { |k| k[:percent]}.reverse %>
<div class="bar-bg">
<% @expense_types.each do |expense_type| %>
    <div style="width:<%= expense_type[:percent] %>%; background: <%= expense_type[:color][:primary] %>"></div>
<% end %>
<div class="clear-float"></div>
</div>

<style>
 .bar-bg {
    height: .5em;
    padding: .5em;
  }
  .bar-bg div {
      height: .5em;
      float: left;
  }
</style>

app/views/expenses/_form.html.erb
<%= form_with model: @expense, local: true do |f| %>
  <div class="field">
    <div class="control amount-control">
      £ <%= f.number_field :amount, step: 0.01, required: true, class: "input amount-input", placeholder: "0.00", control: false %>
    </div>
  </div>

  <div class="field">
    <div class="select">
      <%= f.collection_select(:expense_type_id, ExpenseType.ordered, :id, :name, required: true, selected: 1) %>
    </div>
  </div>
  <div class="field">
    <div class="select">
      <%= f.text_field(:extra_info, maxlength: 20, placeholder: "Extra info") %>
    </div>
  </div>
  <div class="field">
    <div class="select">
      <%= f.date_select :spent_on, required: true, class: "input", order: [:day, :month, :year], start_year: Time.now.year - 1, end_year: Time.now.year + 1%>
    </div>
  </div>
  <%= f.submit class: "button is-primary" %>
<% end %>

<%= link_to "Back", expenses_path %>

app/views/expenses/edit.html.erb
<div class="wrapper">
  <h1>Edit Expense</h1>
  <%= render "form" %>
</div>

app/views/expenses/index.html.erb
<% year =  @expenses.first["year"] + 1 %>
<h1>Monthly Expenses</h1>
<% @expenses.each_with_index do |expense, index| %>
  <% next_expense = @expenses[index + 1] %>

    <% if(year > expense["year"]) %>
    
     <span class="date-tag"> <%= expense["year"] %></span>
      <% year = expense["year"] %>

  <div class="tile-outer">
    <% end %>
    <%= link_to month_expenses_path(year: expense["year"], month: expense["month"]) do %>
      <div class="tile-monthly">
        <div class="monthly-tile-inner"> 
          <p class="title"><%= format_date(expense["month"]) %></p>
          <p class="amount"><%= number_to_currency(expense["amount"], unit: "£") %></p>
          <div class="clear-float"></div>
        </div>
      </div>
    <% end %>
  <% if next_expense.present? %>
    <% if(year > next_expense["year"]) %>
      </div>
    <% else %>
      <hr>
    <% end %>
  <% else %>
    </div>
  <% end %>
<% end %>

app/views/expenses/month.html.erb
<% expense_types = @expenses.map {|x| {name: x.expense_type.name}}.uniq %>
<div class="wrapper">
  <h1><%= format_date(@expenses[0].spent_on.month) %> daily expenses </h1>
  
  <% if @expenses_filtered.present? %>
    <h2>Total: <%= number_to_currency(@expenses_filtered.map { |r| r[:amount] }.sum, unit: "£") %></h2>
    <% else %>
      <h2>Total: <%= number_to_currency(@expenses.map { |r| r[:amount] }.sum, unit: "£") %></h2>
  <% end %>

  <%= expenses_bar(@expenses) %>

  <% current_spent_on = @expenses.first["spent_on"] + 1 %>
  <% if @expenses_filtered.present? %>
    <% @expenses_filtered.each do |expense| %>
      <% if expense["spent_on"] < current_spent_on %>
        <span class="date-tag"><%= expense["spent_on"].strftime("%A") %> <%= ordinalize(expense["spent_on"].day) %></span>
        <% current_spent_on = expense["spent_on"]%>
      <% end %>
      <div class="tile">
        <div class="tile-inner"> 
          <div class="tile-left">
            <div class="expense-icon" style="background:<%= expense.gradient %>;">
              <%= expense.get_name[0,2] %>
            </div>
            <div class="tile-type">
              <%= expense.get_name %>
              <p class="tile-amount"><%= number_to_currency(expense["amount"], unit: "£") %></p>
            </div>
          </div>
        </div>
        <div class="tile-overlay"><%= link_to "Delete", expense_path(expense), data: {:confirm => "Are you sure you want to delete this expense?"}, method: :delete %> <%= link_to "Edit", edit_expense_path(expense) %></div>
      </div>
    <% end %> 
  <% else %>
    <% @expenses.each do |expense| %>
      <% if expense["spent_on"] < current_spent_on %>
        <span class="date-tag"><%= expense["spent_on"].strftime("%A") %> <%= ordinalize(expense["spent_on"].day) %></span>
        <% current_spent_on = expense["spent_on"]%>
      <% end %>
      <div class="tile">
        <div class="tile-inner"> 
          <div class="tile-left">
            <div class="expense-icon" style="background:<%= expense.gradient %>;">
              <%= expense.to_s[0, 2] %>
            </div>
            <div class="tile-type">
              <%= expense %>
              <p class="tile-amount"><%= number_to_currency(expense["amount"], unit: "£") %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %> 
  <% end %>
</div>

app/views/expenses/monthly.html.erb
<% year =  @expenses.first["year"] + 1 %>
<h1>Monthly Expenses</h1>
<% @expenses.each_with_index do |expense, index| %>
  <% next_expense = @expenses[index + 1] %>

    <% if(year > expense["year"]) %>
    
     <span class="date-tag"> <%= expense["year"] %></span>
      <% year = expense["year"] %>

  <div class="tile-outer">
    <% end %>
    <%= link_to month_expenses_path(year: expense["year"], month: expense["month"]) do %>
      <div class="tile-monthly">
        <div class="monthly-tile-inner"> 
          <p class="title"><%= format_date(expense["month"]) %></p>
          <p class="amount"><%= number_to_currency(expense["amount"], unit: "£") %></p>
          <div class="clear-float"></div>
        </div>
      </div>
    <% end %>
  <% if next_expense.present? %>
    <% if(year > next_expense["year"]) %>
      </div>
    <% else %>
      <hr>
    <% end %>
  <% else %>
    </div>
  <% end %>
<% end %>

app/views/expenses/new.html.erb
<div class="wrapper">
  <h1>New Expense</h1>
  <%= render "form" %>
</div>

app/views/expenses/week.html.erb
<% expense_types = @expenses.map {|x| {id: x.expense_type.id, name: x.expense_type.name}}.uniq %>

<div class="wrapper">
  <h1><%= format_date(@expenses[0].spent_on.month) %> week <%= params[:week].to_i + 1 %> expenses </h1>
  
  <h2>Total: <%= number_to_currency(@expenses.map { |r| r[:amount] }.sum, unit: "£") %></h2>

  <%= expenses_bar(@expenses) %>

  <p>
    <b>Filters</b>: 
    <%= link_to "All", week_expenses_path(year: @expenses.first.spent_on.year, month: @expenses.first.spent_on.month, week: params[:week]) %>

    <% expense_types.each do |expense_type| %>
      | 
      <%= link_to week_expenses_path(year: @expenses.first.spent_on.year, month: @expenses.first.spent_on.month, week: params[:week], expense_type: expense_type[:id]) do %>
        <%= expense_type[:name] %>
      <% end %>
    <% end %>
  </p>
  <% current_spent_on = @expenses.first["spent_on"] + 1 %>
  <% @expenses.each do |expense| %>
    <% if expense["spent_on"] < current_spent_on %>
      <span class="date-tag"><%= expense["spent_on"].strftime("%A") %> <%= ordinalize(expense["spent_on"].day) %></span>
      <% current_spent_on = expense["spent_on"]%>
    <% end %>
    <div class="tile">
      <div class="tile-inner"> 
        <div class="tile-left">
          <div class="expense-icon" style="background:<%= expense.gradient %>;">
            <%= expense.to_s[0, 2] %>
          </div>
          <div class="tile-type">
            <%= expense %>
            <p class="tile-amount"><%= number_to_currency(expense["amount"], unit: "£") %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/expenses/weekly.html.erb
<% year =  @expenses.first["year"] + 1 %>
<h1>Weekly Expenses</h1>
<% @expenses.each_with_index do |expense, index| %>
  <% next_expense = @expenses[index + 1] %>

  <% if(year > expense["year"]) %>    
    <span class="date-tag"> <%= expense["year"] %></span>
    <% year = expense["year"] %>
    <div class="tile-outer">
  <% end %>

  <%= link_to week_expenses_path(year: expense["year"], month: expense["month"], week: expense["week"]) do %>
    <div class="tile-monthly">
      <div class="monthly-tile-inner"> 
        <p class="title"><%= format_date(expense["month"]) %> week <%= expense["week"] + 1 %></p>
        <p class="amount"><%= number_to_currency(expense["amount"], unit: "£") %></p>
        <div class="clear-float"></div>
      </div>
    </div>
  <% end %>  
  <% if next_expense.present? %>
    <% if(year > next_expense["year"]) %>
      </div>
    <% else %>
      <hr>
    <% end %>
  <% else %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Expenses Tracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='application-wrapper'>
      <%= yield %>
      <%= link_to "Log Expense", new_expense_path %> | 
      <%= link_to "Expenses Types", expense_types_path %> | 
      <%= link_to "New Expense Type", new_expense_type_path %> |
      <%= link_to "Weekly", weekly_expenses_path %> |
      <%= link_to "Monthly", expenses_path %> |

    </div>
  </body>
</html>